variable "location" {}
variable "slot_name" {}
variable "app_service_id" {}
variable "dotnet_version" {}
variable "app_settings" {}
variable "connection_string_name" {}
variable "connection_string_type" {}
variable "connection_string_value" {}
variable "tags" {}
